# New ports collection makefile for:	p5-MooseX-Attribute-ENV
# Date created:				18 November 2010
# Whom: 				alan <Alan@Wave2.org>
#
# $FreeBSD: ports/devel/p5-MooseX-Attribute-ENV/Makefile,v 1.2 2011/09/17 07:06:29 sunpoet Exp $
#

PORTNAME=	MooseX-Attribute-ENV
PORTVERSION=	0.02
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	Alan@Wave2.org
COMMENT=	Set default of an attribute to a value from %ENV

RUN_DEPENDS=	p5-Moose>=1.19:${PORTSDIR}/devel/p5-Moose
TEST_DEPENDS=	p5-Moose>=1.19:${PORTSDIR}/devel/p5-Moose

PERL_CONFIGURE=	yes

MAN3=		MooseX::Attribute::ENV.3

.include <bsd.port.mk>
